language: node_js
sudo: false

cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages

before_cache:
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.tar

matrix:
  include:
    - env: GHCVER=7.10.2 TEST_PART=CORE-GHC
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE-GHC"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=CORE-CONC
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE-CONC"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=CORE-INTEGER
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE-INTEGER"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=CORE-PKG
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE-PKG"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=CORE-FAY
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE-FAY"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=PROFILING
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE1"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.2 TEST_PART=GHCJS
      node_js:
        - "4.0"
      compiler: ": #GHC 7.10.2 CORE1"
      addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.2,alex-3.1.4,happy-1.19.5], sources: [hvr-ghc]}}

before_install:
  - unset CC
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.5/bin:$PATH
  - export GHCJS_BOOTING=1
  - export GHCJS_BOOTING_STAGE1=1
  - export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:/opt/alex/3.1.4/bin:/opt/happy/1.19.5/bin:$PATH

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - if [ -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz ];
    then
      zcat $HOME/.cabal/packages/hackage.haskell.org/00-index.tar.gz >
           $HOME/.cabal/packages/hackage.haskell.org/00-index.tar;
    fi
  - travis_retry cabal update -v
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
  - if [ -n "$STACKAGE" ]; then curl --silent https://www.stackage.org/$STACKAGE/cabal.config | grep -v 'hpack ==' > cabal.config; fi
  - if [ -n "$CABALCONFIG" ]; then cp $CABALCONFIG cabal.config; fi
  - cabal install --only-dependencies --enable-tests --enable-benchmarks --dry -v > installplan.txt
  - sed -i -e '1,/^Resolving /d' installplan.txt; cat installplan.txt

  # check whether current requested install-plan matches cached package-db snapshot
  - if diff -u installplan.txt $HOME/.cabsnap/installplan.txt;
    then
      echo "cabal build-cache HIT";
      rm -rfv .ghc;
      cp -a $HOME/.cabsnap/ghc $HOME/.ghc;
      cp -a $HOME/.cabsnap/lib $HOME/.cabsnap/share $HOME/.cabsnap/bin $HOME/.cabal/;
    else
      echo "cabal build-cache MISS";
      rm -rf $HOME/.cabsnap;
      mkdir -p $HOME/.ghc $HOME/.cabal/lib $HOME/.cabal/share $HOME/.cabal/bin;
      cabal install --only-dependencies --enable-tests --enable-benchmarks;
    fi

  # Install and boot ghcjs
  - cabal install --enable-tests --enable-benchmarks -v -j1 --ghc-options="+RTS -c -RTS"
  - ghcjs --version
  - ghcjs-boot --version
  - ./test/runTravis.sh boot
  - ghcjs-pkg list

script:
  - ./test/runTravis.sh test

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
    skip_join: true
  email: true
